import "./ui/globals.css";
import { Providers } from "./providers";
import { fonts } from './fonts'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={fonts.rubik.variable}>
      <body style={{background: "#151c2c"}}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
